/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SmeltLabRouteImport } from './routes/smelt-lab'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as EditorialExampleRouteImport } from './routes/editorial-example'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge.index'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as InstitutesIndexRouteImport } from './routes/institutes.index'
import { Route as VisualEditorialBlocksRouteImport } from './routes/visual/editorial-blocks'
import { Route as LibrarySlugRouteImport } from './routes/library.$slug'
import { Route as KnowledgeSearchRouteImport } from './routes/knowledge.search'
import { Route as KnowledgePathwaysRouteImport } from './routes/knowledge.pathways'
import { Route as KnowledgeGlossaryRouteImport } from './routes/knowledge.glossary'
import { Route as KnowledgeCompareRouteImport } from './routes/knowledge.compare'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as InstitutesSlugRouteImport } from './routes/institutes.$slug'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as JournalTagTagRouteImport } from './routes/journal.tag.$tag'
import { Route as JournalCategoryCategoryRouteImport } from './routes/journal.category.$category'
import { Route as InstitutesSlugChaptersChapterRouteImport } from './routes/institutes.$slug.chapters.$chapter'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SmeltLabRoute = SmeltLabRouteImport.update({
  id: '/smelt-lab',
  path: '/smelt-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialExampleRoute = EditorialExampleRouteImport.update({
  id: '/editorial-example',
  path: '/editorial-example',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryRoute,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KnowledgeRoute,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JournalRoute,
} as any)
const InstitutesIndexRoute = InstitutesIndexRouteImport.update({
  id: '/institutes/',
  path: '/institutes/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualEditorialBlocksRoute = VisualEditorialBlocksRouteImport.update({
  id: '/visual/editorial-blocks',
  path: '/visual/editorial-blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarySlugRoute = LibrarySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LibraryRoute,
} as any)
const KnowledgeSearchRoute = KnowledgeSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgePathwaysRoute = KnowledgePathwaysRouteImport.update({
  id: '/pathways',
  path: '/pathways',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeGlossaryRoute = KnowledgeGlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeCompareRoute = KnowledgeCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => KnowledgeRoute,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)
const InstitutesSlugRoute = InstitutesSlugRouteImport.update({
  id: '/institutes/$slug',
  path: '/institutes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const JournalTagTagRoute = JournalTagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => JournalRoute,
} as any)
const JournalCategoryCategoryRoute = JournalCategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => JournalRoute,
} as any)
const InstitutesSlugChaptersChapterRoute =
  InstitutesSlugChaptersChapterRouteImport.update({
    id: '/chapters/$chapter',
    path: '/chapters/$chapter',
    getParentRoute: () => InstitutesSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/editorial-example': typeof EditorialExampleRoute
  '/governance': typeof GovernanceRoute
  '/journal': typeof JournalRouteWithChildren
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/library': typeof LibraryRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smelt-lab': typeof SmeltLabRoute
  '/terms': typeof TermsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/institutes/$slug': typeof InstitutesSlugRouteWithChildren
  '/journal/$slug': typeof JournalSlugRoute
  '/knowledge/compare': typeof KnowledgeCompareRoute
  '/knowledge/glossary': typeof KnowledgeGlossaryRoute
  '/knowledge/pathways': typeof KnowledgePathwaysRoute
  '/knowledge/search': typeof KnowledgeSearchRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/visual/editorial-blocks': typeof VisualEditorialBlocksRoute
  '/institutes/': typeof InstitutesIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/journal/category/$category': typeof JournalCategoryCategoryRoute
  '/journal/tag/$tag': typeof JournalTagTagRoute
  '/institutes/$slug/chapters/$chapter': typeof InstitutesSlugChaptersChapterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/editorial-example': typeof EditorialExampleRoute
  '/governance': typeof GovernanceRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smelt-lab': typeof SmeltLabRoute
  '/terms': typeof TermsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/institutes/$slug': typeof InstitutesSlugRouteWithChildren
  '/journal/$slug': typeof JournalSlugRoute
  '/knowledge/compare': typeof KnowledgeCompareRoute
  '/knowledge/glossary': typeof KnowledgeGlossaryRoute
  '/knowledge/pathways': typeof KnowledgePathwaysRoute
  '/knowledge/search': typeof KnowledgeSearchRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/visual/editorial-blocks': typeof VisualEditorialBlocksRoute
  '/institutes': typeof InstitutesIndexRoute
  '/journal': typeof JournalIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/library': typeof LibraryIndexRoute
  '/journal/category/$category': typeof JournalCategoryCategoryRoute
  '/journal/tag/$tag': typeof JournalTagTagRoute
  '/institutes/$slug/chapters/$chapter': typeof InstitutesSlugChaptersChapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/editorial-example': typeof EditorialExampleRoute
  '/governance': typeof GovernanceRoute
  '/journal': typeof JournalRouteWithChildren
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/library': typeof LibraryRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smelt-lab': typeof SmeltLabRoute
  '/terms': typeof TermsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/institutes/$slug': typeof InstitutesSlugRouteWithChildren
  '/journal/$slug': typeof JournalSlugRoute
  '/knowledge/compare': typeof KnowledgeCompareRoute
  '/knowledge/glossary': typeof KnowledgeGlossaryRoute
  '/knowledge/pathways': typeof KnowledgePathwaysRoute
  '/knowledge/search': typeof KnowledgeSearchRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/visual/editorial-blocks': typeof VisualEditorialBlocksRoute
  '/institutes/': typeof InstitutesIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/journal/category/$category': typeof JournalCategoryCategoryRoute
  '/journal/tag/$tag': typeof JournalTagTagRoute
  '/institutes/$slug/chapters/$chapter': typeof InstitutesSlugChaptersChapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/editorial-example'
    | '/governance'
    | '/journal'
    | '/knowledge'
    | '/library'
    | '/privacy'
    | '/sitemap.xml'
    | '/smelt-lab'
    | '/terms'
    | '/profile'
    | '/institutes/$slug'
    | '/journal/$slug'
    | '/knowledge/compare'
    | '/knowledge/glossary'
    | '/knowledge/pathways'
    | '/knowledge/search'
    | '/library/$slug'
    | '/visual/editorial-blocks'
    | '/institutes/'
    | '/journal/'
    | '/knowledge/'
    | '/library/'
    | '/journal/category/$category'
    | '/journal/tag/$tag'
    | '/institutes/$slug/chapters/$chapter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/editorial-example'
    | '/governance'
    | '/privacy'
    | '/sitemap.xml'
    | '/smelt-lab'
    | '/terms'
    | '/profile'
    | '/institutes/$slug'
    | '/journal/$slug'
    | '/knowledge/compare'
    | '/knowledge/glossary'
    | '/knowledge/pathways'
    | '/knowledge/search'
    | '/library/$slug'
    | '/visual/editorial-blocks'
    | '/institutes'
    | '/journal'
    | '/knowledge'
    | '/library'
    | '/journal/category/$category'
    | '/journal/tag/$tag'
    | '/institutes/$slug/chapters/$chapter'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/editorial-example'
    | '/governance'
    | '/journal'
    | '/knowledge'
    | '/library'
    | '/privacy'
    | '/sitemap.xml'
    | '/smelt-lab'
    | '/terms'
    | '/_authenticated/profile'
    | '/institutes/$slug'
    | '/journal/$slug'
    | '/knowledge/compare'
    | '/knowledge/glossary'
    | '/knowledge/pathways'
    | '/knowledge/search'
    | '/library/$slug'
    | '/visual/editorial-blocks'
    | '/institutes/'
    | '/journal/'
    | '/knowledge/'
    | '/library/'
    | '/journal/category/$category'
    | '/journal/tag/$tag'
    | '/institutes/$slug/chapters/$chapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EditorialExampleRoute: typeof EditorialExampleRoute
  GovernanceRoute: typeof GovernanceRoute
  JournalRoute: typeof JournalRouteWithChildren
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  LibraryRoute: typeof LibraryRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SmeltLabRoute: typeof SmeltLabRoute
  TermsRoute: typeof TermsRoute
  InstitutesSlugRoute: typeof InstitutesSlugRouteWithChildren
  VisualEditorialBlocksRoute: typeof VisualEditorialBlocksRoute
  InstitutesIndexRoute: typeof InstitutesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smelt-lab': {
      id: '/smelt-lab'
      path: '/smelt-lab'
      fullPath: '/smelt-lab'
      preLoaderRoute: typeof SmeltLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-example': {
      id: '/editorial-example'
      path: '/editorial-example'
      fullPath: '/editorial-example'
      preLoaderRoute: typeof EditorialExampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/journal/': {
      id: '/journal/'
      path: '/'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof JournalRoute
    }
    '/institutes/': {
      id: '/institutes/'
      path: '/institutes'
      fullPath: '/institutes/'
      preLoaderRoute: typeof InstitutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visual/editorial-blocks': {
      id: '/visual/editorial-blocks'
      path: '/visual/editorial-blocks'
      fullPath: '/visual/editorial-blocks'
      preLoaderRoute: typeof VisualEditorialBlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$slug': {
      id: '/library/$slug'
      path: '/$slug'
      fullPath: '/library/$slug'
      preLoaderRoute: typeof LibrarySlugRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/knowledge/search': {
      id: '/knowledge/search'
      path: '/search'
      fullPath: '/knowledge/search'
      preLoaderRoute: typeof KnowledgeSearchRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/pathways': {
      id: '/knowledge/pathways'
      path: '/pathways'
      fullPath: '/knowledge/pathways'
      preLoaderRoute: typeof KnowledgePathwaysRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/glossary': {
      id: '/knowledge/glossary'
      path: '/glossary'
      fullPath: '/knowledge/glossary'
      preLoaderRoute: typeof KnowledgeGlossaryRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/compare': {
      id: '/knowledge/compare'
      path: '/compare'
      fullPath: '/knowledge/compare'
      preLoaderRoute: typeof KnowledgeCompareRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
    '/institutes/$slug': {
      id: '/institutes/$slug'
      path: '/institutes/$slug'
      fullPath: '/institutes/$slug'
      preLoaderRoute: typeof InstitutesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/journal/tag/$tag': {
      id: '/journal/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/journal/tag/$tag'
      preLoaderRoute: typeof JournalTagTagRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/category/$category': {
      id: '/journal/category/$category'
      path: '/category/$category'
      fullPath: '/journal/category/$category'
      preLoaderRoute: typeof JournalCategoryCategoryRouteImport
      parentRoute: typeof JournalRoute
    }
    '/institutes/$slug/chapters/$chapter': {
      id: '/institutes/$slug/chapters/$chapter'
      path: '/chapters/$chapter'
      fullPath: '/institutes/$slug/chapters/$chapter'
      preLoaderRoute: typeof InstitutesSlugChaptersChapterRouteImport
      parentRoute: typeof InstitutesSlugRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
  JournalCategoryCategoryRoute: typeof JournalCategoryCategoryRoute
  JournalTagTagRoute: typeof JournalTagTagRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
  JournalIndexRoute: JournalIndexRoute,
  JournalCategoryCategoryRoute: JournalCategoryCategoryRoute,
  JournalTagTagRoute: JournalTagTagRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

interface KnowledgeRouteChildren {
  KnowledgeCompareRoute: typeof KnowledgeCompareRoute
  KnowledgeGlossaryRoute: typeof KnowledgeGlossaryRoute
  KnowledgePathwaysRoute: typeof KnowledgePathwaysRoute
  KnowledgeSearchRoute: typeof KnowledgeSearchRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeCompareRoute: KnowledgeCompareRoute,
  KnowledgeGlossaryRoute: KnowledgeGlossaryRoute,
  KnowledgePathwaysRoute: KnowledgePathwaysRoute,
  KnowledgeSearchRoute: KnowledgeSearchRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

interface LibraryRouteChildren {
  LibrarySlugRoute: typeof LibrarySlugRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibrarySlugRoute: LibrarySlugRoute,
  LibraryIndexRoute: LibraryIndexRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

interface InstitutesSlugRouteChildren {
  InstitutesSlugChaptersChapterRoute: typeof InstitutesSlugChaptersChapterRoute
}

const InstitutesSlugRouteChildren: InstitutesSlugRouteChildren = {
  InstitutesSlugChaptersChapterRoute: InstitutesSlugChaptersChapterRoute,
}

const InstitutesSlugRouteWithChildren = InstitutesSlugRoute._addFileChildren(
  InstitutesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EditorialExampleRoute: EditorialExampleRoute,
  GovernanceRoute: GovernanceRoute,
  JournalRoute: JournalRouteWithChildren,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  LibraryRoute: LibraryRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SmeltLabRoute: SmeltLabRoute,
  TermsRoute: TermsRoute,
  InstitutesSlugRoute: InstitutesSlugRouteWithChildren,
  VisualEditorialBlocksRoute: VisualEditorialBlocksRoute,
  InstitutesIndexRoute: InstitutesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
