/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as EditorialExampleRouteImport } from './routes/editorial-example'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstitutesIndexRouteImport } from './routes/institutes.index'
import { Route as VisualEditorialBlocksRouteImport } from './routes/visual/editorial-blocks'
import { Route as InstitutesSlugRouteImport } from './routes/institutes.$slug'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as InstitutesSlugChaptersChapterRouteImport } from './routes/institutes.$slug.chapters.$chapter'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialExampleRoute = EditorialExampleRouteImport.update({
  id: '/editorial-example',
  path: '/editorial-example',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutesIndexRoute = InstitutesIndexRouteImport.update({
  id: '/institutes/',
  path: '/institutes/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualEditorialBlocksRoute = VisualEditorialBlocksRouteImport.update({
  id: '/visual/editorial-blocks',
  path: '/visual/editorial-blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutesSlugRoute = InstitutesSlugRouteImport.update({
  id: '/institutes/$slug',
  path: '/institutes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const InstitutesSlugChaptersChapterRoute =
  InstitutesSlugChaptersChapterRouteImport.update({
    id: '/chapters/$chapter',
    path: '/chapters/$chapter',
    getParentRoute: () => InstitutesSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/editorial-example': typeof EditorialExampleRoute
  '/governance': typeof GovernanceRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/institutes/$slug': typeof InstitutesSlugRouteWithChildren
  '/visual/editorial-blocks': typeof VisualEditorialBlocksRoute
  '/institutes/': typeof InstitutesIndexRoute
  '/institutes/$slug/chapters/$chapter': typeof InstitutesSlugChaptersChapterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/editorial-example': typeof EditorialExampleRoute
  '/governance': typeof GovernanceRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/institutes/$slug': typeof InstitutesSlugRouteWithChildren
  '/visual/editorial-blocks': typeof VisualEditorialBlocksRoute
  '/institutes': typeof InstitutesIndexRoute
  '/institutes/$slug/chapters/$chapter': typeof InstitutesSlugChaptersChapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/editorial-example': typeof EditorialExampleRoute
  '/governance': typeof GovernanceRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/institutes/$slug': typeof InstitutesSlugRouteWithChildren
  '/visual/editorial-blocks': typeof VisualEditorialBlocksRoute
  '/institutes/': typeof InstitutesIndexRoute
  '/institutes/$slug/chapters/$chapter': typeof InstitutesSlugChaptersChapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/editorial-example'
    | '/governance'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/profile'
    | '/institutes/$slug'
    | '/visual/editorial-blocks'
    | '/institutes/'
    | '/institutes/$slug/chapters/$chapter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/editorial-example'
    | '/governance'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/profile'
    | '/institutes/$slug'
    | '/visual/editorial-blocks'
    | '/institutes'
    | '/institutes/$slug/chapters/$chapter'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/editorial-example'
    | '/governance'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/profile'
    | '/institutes/$slug'
    | '/visual/editorial-blocks'
    | '/institutes/'
    | '/institutes/$slug/chapters/$chapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EditorialExampleRoute: typeof EditorialExampleRoute
  GovernanceRoute: typeof GovernanceRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  InstitutesSlugRoute: typeof InstitutesSlugRouteWithChildren
  VisualEditorialBlocksRoute: typeof VisualEditorialBlocksRoute
  InstitutesIndexRoute: typeof InstitutesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-example': {
      id: '/editorial-example'
      path: '/editorial-example'
      fullPath: '/editorial-example'
      preLoaderRoute: typeof EditorialExampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutes/': {
      id: '/institutes/'
      path: '/institutes'
      fullPath: '/institutes/'
      preLoaderRoute: typeof InstitutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visual/editorial-blocks': {
      id: '/visual/editorial-blocks'
      path: '/visual/editorial-blocks'
      fullPath: '/visual/editorial-blocks'
      preLoaderRoute: typeof VisualEditorialBlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutes/$slug': {
      id: '/institutes/$slug'
      path: '/institutes/$slug'
      fullPath: '/institutes/$slug'
      preLoaderRoute: typeof InstitutesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/institutes/$slug/chapters/$chapter': {
      id: '/institutes/$slug/chapters/$chapter'
      path: '/chapters/$chapter'
      fullPath: '/institutes/$slug/chapters/$chapter'
      preLoaderRoute: typeof InstitutesSlugChaptersChapterRouteImport
      parentRoute: typeof InstitutesSlugRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface InstitutesSlugRouteChildren {
  InstitutesSlugChaptersChapterRoute: typeof InstitutesSlugChaptersChapterRoute
}

const InstitutesSlugRouteChildren: InstitutesSlugRouteChildren = {
  InstitutesSlugChaptersChapterRoute: InstitutesSlugChaptersChapterRoute,
}

const InstitutesSlugRouteWithChildren = InstitutesSlugRoute._addFileChildren(
  InstitutesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EditorialExampleRoute: EditorialExampleRoute,
  GovernanceRoute: GovernanceRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  InstitutesSlugRoute: InstitutesSlugRouteWithChildren,
  VisualEditorialBlocksRoute: VisualEditorialBlocksRoute,
  InstitutesIndexRoute: InstitutesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
